spring:
  application:
    name: api-gateway

server:
  port: 80

zuul:
  routes:
    greeting:
      path: /greeting/**
      serviceId: greeting-service
    goodbye:
      path: /goodbye/**
      serviceId: goodbye-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}