spring:
  application:
    name: user-service
  jpa:
    databasePlatform: org.hibernate.dialect.Oracle10gDialect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: igor
    password: mexos
    driverClassName: oracle.jdbc.driver.OracleDriver

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    instanceId: ${spring.application.name}-1